"""create realty tables

Revision ID: 15edf54754bb
Revises: f1adceadd37c
Create Date: 2024-05-10 17:44:33.595919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15edf54754bb'
down_revision: Union[str, None] = 'f1adceadd37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('realty_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('square', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('builder', sa.String(), nullable=True),
    sa.Column('rc', sa.String(), nullable=True),
    sa.Column('turn', sa.String(), nullable=True),
    sa.Column('entrance', sa.String(), nullable=True),
    sa.Column('heating', sa.String(), nullable=True),
    sa.Column('documents', sa.String(), nullable=True),
    sa.Column('material_manufacture', sa.String(), nullable=True),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('settlement', sa.String(), nullable=True),
    sa.Column('house_type', sa.String(), nullable=True),
    sa.Column('land_area_object', sa.String(), nullable=True),
    sa.Column('communications', sa.String(), nullable=True),
    sa.Column('appointment', sa.String(), nullable=True),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('tenants_object', sa.String(), nullable=True),
    sa.Column('comfort', sa.String(), nullable=True),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('seller_phone_number', sa.String(), nullable=True),
    sa.Column('seller_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realty_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realty_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['realty_id'], ['realties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realty_images')
    op.drop_table('realties')
    # ### end Alembic commands ###
