"""update table realties

Revision ID: 40e416aa670f
Revises: 7ca7ee7f709a
Create Date: 2024-05-12 20:30:03.759165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e416aa670f'
down_revision: Union[str, None] = '7ca7ee7f709a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realties', sa.Column('realty_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realties', 'realty_type')
    # ### end Alembic commands ###
