"""update table realties

Revision ID: 7ca7ee7f709a
Revises: 15edf54754bb
Create Date: 2024-05-12 20:09:36.073560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca7ee7f709a'
down_revision: Union[str, None] = '15edf54754bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realties', sa.Column('material_manufacture_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realties', 'material_manufacture_2')
    # ### end Alembic commands ###
